CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT chk_customers_name CHECK (length(btrim(name)) > 0),
    CONSTRAINT chk_customers_email_lower CHECK (email = lower(btrim(email))),
    CONSTRAINT chk_customers_email_length CHECK (length(email) > 0)
);

CREATE INDEX idx_customers_created_at_id ON customers (created_at DESC, id DESC);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(8, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_products_name CHECK (length(btrim(name)) > 0),
    CONSTRAINT chk_products_price CHECK (price >= 0.01 AND price <= 999999.99)
);

CREATE INDEX idx_products_created_at_id ON products (created_at DESC, id DESC);
CREATE INDEX idx_products_active_created_at_id ON products (active, created_at DESC, id DESC);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers (id) ON DELETE RESTRICT,
    status VARCHAR(16) NOT NULL,
    total NUMERIC(14, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_orders_status CHECK (status IN ('CREATED', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_orders_total CHECK (total >= 0.01 AND total <= 99899999001.00)
);

CREATE INDEX idx_orders_created_at_id ON orders (created_at DESC, id DESC);
CREATE INDEX idx_orders_customer_created_at_id ON orders (customer_id, created_at DESC, id DESC);
CREATE INDEX idx_orders_status_created_at_id ON orders (status, created_at DESC, id DESC);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products (id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(8, 2) NOT NULL,
    subtotal NUMERIC(14, 2) NOT NULL,
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_items_quantity CHECK (quantity BETWEEN 1 AND 999),
    CONSTRAINT chk_order_items_unit_price CHECK (unit_price >= 0.01 AND unit_price <= 999999.99),
    CONSTRAINT chk_order_items_subtotal CHECK (subtotal = unit_price * quantity)
);

CREATE INDEX idx_order_items_product_id ON order_items (product_id);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    order_id BIGINT NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    type VARCHAR(32) NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_notifications_event_id UNIQUE (event_id),
    CONSTRAINT uk_notifications_order_type UNIQUE (order_id, type),
    CONSTRAINT chk_notifications_type CHECK (type = 'ORDER_CREATED')
);

CREATE INDEX idx_notifications_created_at_id ON notifications (created_at DESC, id DESC);
CREATE INDEX idx_notifications_order_created_at_id ON notifications (order_id, created_at DESC, id DESC);

CREATE TABLE outbox_events (
    event_id UUID PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id) ON DELETE RESTRICT,
    event_type VARCHAR(32) NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts BIGINT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    last_error VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    CONSTRAINT uk_outbox_order_event_type UNIQUE (order_id, event_type),
    CONSTRAINT chk_outbox_event_type CHECK (event_type = 'ORDER_CREATED'),
    CONSTRAINT chk_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED')),
    CONSTRAINT chk_outbox_attempts CHECK (attempts >= 0),
    CONSTRAINT chk_outbox_published CHECK (
        (status = 'PENDING' AND published_at IS NULL)
        OR (status = 'PUBLISHED' AND published_at IS NOT NULL)
    ),
    CONSTRAINT chk_outbox_payload CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX idx_outbox_pending ON outbox_events (next_attempt_at, created_at, event_id)
    WHERE status = 'PENDING';
