package com.eventflow.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    CUSTOMER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    ORDER_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    DUPLICATE_CUSTOMER_EMAIL,
    PRODUCT_INACTIVE,
    INVALID_ORDER_STATUS_TRANSITION,
    UNSUPPORTED_MEDIA_TYPE,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
